import Head from 'next/head'
import {Inter} from '@next/font/google'
import Title from "@/components/Title";
import Search from "@/components/Search";
import {useEffect, useState} from "react";
import LoginForm from "@/components/LoginForm";
import auth from "../firebase/connect"
import Swal from "sweetalert2";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const [session, setSession] = useState({
        LoggedIn: false,
        User: null,
        error: null
    })

    const [fontsLoaded, setFontsLoaded] = useState(false)

    useEffect(() => {
        auth.onAuthStateChanged((user: any) => {
            if (user) {
                setSession({
                    LoggedIn: true,
                    User: user,
                    error: null
                })
            } else {
                setSession({
                    LoggedIn: false,
                    User: null,
                    error: null
                })
            }
            setFontsLoaded(true)
        })
    },[])

    //loading fonts with sweet alert
    if(!fontsLoaded){
        setTimeout(() =>{
            Swal.close()
        },500)
        Swal.fire({
            title: 'Checking your session',
            html: 'Please wait...',
            allowOutsideClick: false,
            didOpen: () => {
                Swal.showLoading()
            }
        })
        return null
    }
return (
    <>
        <Head>
            <title>PM2.5 Database</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        {
            session.LoggedIn ? (<div className={"container"}>
                <Title setSession={setSession} session={session}/>
                <Search/>
            </div>) : (<LoginForm setSession={setSession}/>)
        }
    </>
)
}
